/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package de.tinloaf.iris.mobileapp;

public final class Manifest {
    public static final class permission {
        public static final String C2D_MESSAGE="de.tinloaf.iris.mobileapp.permission.C2D_MESSAGE";
    }
}
